### ISSUE TITLE
SNMP v3 trapserver not working

### ISSUE THREAD

**Issue by kvdk87** [gosnmp/gosnmp#235]
Tried setting V3 Params to trapserver but it is not receiving SNMP v3 traps.

tl := g.NewTrapListener()
tl.Params = &g.GoSNMP{
Port:          162,
Version:       g.Version3,
Timeout:       time.Duration(30) * time.Second,
SecurityModel: g.UserSecurityModel,
MsgFlags:      g.AuthPriv,
SecurityParameters: &g.UsmSecurityParameters{UserName: "user",
AuthenticationProtocol:   g.SHA,
AuthenticationPassphrase: "user123",
PrivacyProtocol:          g.DES,
PrivacyPassphrase:        "user123",
},
}
tl.OnNewTrap = myTrapHandler

**Comment by soniah** [comment]
👍

**Comment by soniah** [comment]
See also https://github.com/soniah/gosnmp/issues/236

**Comment by SuperQ** [comment]
I'm posting to all open issues that we now have a community maintainer effort going. If this issue is still valid, please post an update.

**Comment by reimda** [comment]
This could be the same as #284
