### ISSUE TITLE
Code fails with v1.26.0 but works with version v1.25.0

### ISSUE THREAD

**Issue by rolinux** [gosnmp/gosnmp#236]
**Thank you very much for the amazing library**

Last night I spend few hours trying to figure out why code from last year didn't compile anymore and I was getting the following error (after using the HEAD or the `git checkout v1.26.0` tag):

```
> go run main.go
2020/05/21 16:49:08 Get() err: recover: crypto: requested hash function #3 is unavailable
Stack:goroutine 1 [running]:
github.com/soniah/gosnmp.(*GoSNMP).send.func1(0xc00003ed70)
	/Users/radu/devel/go/src/github.com/soniah/gosnmp/marshal.go:318 +0xa1
panic(0x116d7e0, 0xc00011a8b0)
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/panic.go:969 +0x166
crypto.Hash.New(0x3, 0x1170801, 0xc000136360)
	/usr/local/Cellar/go/1.14.3/libexec/src/crypto/crypto.go:89 +0x102
crypto/hmac.New(0xc00003ea30, 0x0, 0x0, 0x0, 0x11708c0, 0x1)
	/usr/local/Cellar/go/1.14.3/libexec/src/crypto/hmac/hmac.go:72 +0x45
github.com/soniah/gosnmp.(*UsmSecurityParameters).calcPacketDigest(0xc00011eea0, 0xc000172000, 0x69, 0x69, 0x0, 0x0, 0x5)
	/Users/radu/devel/go/src/github.com/soniah/gosnmp/v3_usm.go:577 +0x1d6
github.com/soniah/gosnmp.(*UsmSecurityParameters).isAuthentic(0xc00011eea0, 0xc000172000, 0x69, 0x69, 0xc00016a2a0, 0x1149f51, 0x119e7e0, 0xc00011f1e0)
	/Users/radu/devel/go/src/github.com/soniah/gosnmp/v3_usm.go:617 +0x85
github.com/soniah/gosnmp.(*GoSNMP).testAuthentication(0xc000130240, 0xc000172000, 0x69, 0x69, 0xc00016a2a0, 0x36, 0x0)
	/Users/radu/devel/go/src/github.com/soniah/gosnmp/v3.go:96 +0x8e
github.com/soniah/gosnmp.(*GoSNMP).sendOneRequest(0xc000130240, 0xc00016a0e0, 0x100db01, 0x10, 0x116f660, 0x1361e01)
	/Users/radu/devel/go/src/github.com/soniah/gosnmp/marshal.go:253 +0xbd9
github.com/soniah/gosnmp.(*GoSNMP).negotiateInitialSecurityParameters(0xc000130240, 0xc00016a000, 0xc00003ed01, 0x100db18, 0xe0)
	/Users/radu/devel/go/src/github.com/soniah/gosnmp/v3.go:133 +0xe9
github.com/soniah/gosnmp.(*GoSNMP).send(0xc000130240, 0xc00016a000, 0xc000168001, 0x0, 0x0, 0x0)
	/Users/radu/devel/go/src/github.com/soniah/gosnmp/marshal.go:334 +0x7d2
github.com/soniah/gosnmp.(*GoSNMP).Get(0xc000130240, 0xc00003ee88, 0x1, 0x1, 0x0, 0x1, 0x0)
	/Users/radu/devel/go/src/github.com/soniah/gosnmp/gosnmp.go:361 +0x18d
main.getTemperature(0x0)
	/Users/radu/devel/go/src/poeCooling/main.go:91 +0x238
main.main()
	/Users/radu/devel/go/src/poeCooling/main.go:140 +0x26

exit status 1
```

But with `git checkout v1.25.0` I get the following correct result:

```
go run main.go
2020/05/21 16:50:39 Debug: temperature ok at 67, will keep it running
```

The code is mostly from an example from last year with the only small changes (OID, target, user and password):

```go
func getTemperature() int {
	// build our own GoSNMP struct, rather than using g.Default
	params := &g.GoSNMP{
		Target:        poeSwitchIP,
		Port:          161,
		Version:       g.Version3,
		Timeout:       time.Duration(30) * time.Second,
		SecurityModel: g.UserSecurityModel,
		MsgFlags:      g.AuthPriv,
		SecurityParameters: &g.UsmSecurityParameters{UserName: snmpUser,
			AuthenticationProtocol:   g.SHA,
			AuthenticationPassphrase: snmpPassword,
			PrivacyProtocol:          g.AES,
			PrivacyPassphrase:        snmpPassword,
		},
	}
	err := params.Connect()
	if err != nil {
		log.Fatalf("Connect() err: %v", err)
	}
	defer params.Conn.Close()

	oids := []string{temperatureOID}
	result, err2 := params.Get(oids) // Get() accepts up to g.MAX_OIDS
	if err2 != nil {
		log.Fatalf("Get() err: %v", err2)
	}

	for _, variable := range result.Variables {
		return variable.Value.(int)
	}
	return 0
}
```

The target OID is `temperatureOID = "1.3.6.1.4.1.4413.1.1.43.1.8.1.5.1.1"` and the hardware is an [Ubiquiti Unifi switch](https://www.ui.com/unifi-switching/unifi-switch-8-150w/) with snmpv3 enabled.

I tried to add the crypto libraries and when the errors were no longer showing it was getting somehow another OID result and that result was increasing at every run.

If this a bug then I can help debug further. Or maybe if some major changes were done in code between `v1.25.0` and `v1.26.0` then it needs rewrite/porting of code.

**Comment by soniah** [comment]
Thank you @rolinux for your nice comments 🎂 

In a nutshell - I have to balance new features vs code quality, and I don't have enough time to go through all the PRs in enough detail, because I've also got a job 😄 

So some PR's between 1.25 and 1.26 have added features but also broken parts of `snmpv3`, so probably better to stick to 1.25 (unless you've got time to find the bugs!).

In the meantime I've been adding lots of linting to the build, to help improve it. But really I need time to write a proper test/build system using containers for both local and travis, so I can dig into the issues.

**Comment by StefanHauth** [comment]
I think the reason for this issue is, that in https://github.com/soniah/gosnmp/commit/c08a587d80ec99f83c7c4b36df476629ffeec48c#diff-e440d0caa5411e74256ddc91229b73e2 the imports of the crypto functions have been removed. These are needed. 

Please try adding 
`import _ crypto.SHA1`
to your application. Do likewise if you need other hash functions as well. It might be at least a workaround.

**Comment by rolinux** [comment]
As stated in the initial comment, I was able to go around the crypto library errors but then it was failing silently by returning another OID result and not the target one. I can debug further and add here the target and the resulted OID but indeed looks like an issue related to latest version code change.


> I tried to add the crypto libraries and when the errors were no longer showing it was getting somehow another OID result and that result was increasing at every run.

**Comment by StefanHauth** [comment]
Could you please let us know which OID you receive? There could be something wrong with the authentication (wrong digest in message?), in which case the returned OID and its value could give us a hint where to look.

**Comment by rolinux** [comment]
Target OID is "1.3.6.1.4.1.4413.1.1.43.1.8.1.5.1.1" and the returned OID is ".1.3.6.1.6.3.15.1.1.5.0".

Code snippet:

```go
	oids := []string{temperatureOID}
	result, err2 := params.Get(oids) // Get() accepts up to g.MAX_OIDS
	if err2 != nil {
		log.Fatalf("Get() err: %v", err2)
	}

	fmt.Printf("Debug: %v\n", result.Variables[0])
	fmt.Printf("Debug name: %v\n", result.Variables[0].Name)
	fmt.Printf("Debug value: %v\n", result.Variables[0].Value)
```

And the output is:

```
Debug: {.1.3.6.1.6.3.15.1.1.5.0 Counter32 72 0xc0000b80a0}
Debug name: .1.3.6.1.6.3.15.1.1.5.0
Debug value: 72
```

Unsure if there is any relationship between those 2 OIDs but the value is a counter that increases at every run (I probably run it 72 times :)

**Comment by StefanHauth** [comment]
Thanx! This confirms my suspicion. That's the OID of usmStatsWrongDigests (http://www.oid-info.com/cgi-bin/display?oid=1.3.6.1.6.3.15.1.1.5&action=display). It means that there's something wrong with the message's digest.
If your code works with 1.25.0 and not with 1.26.0, then I've to check the digest calculation once more.

Just out of curiosity: could you please try to run your code against demo.snmplabs.com using
User:  usr-sha-aes
AuthKey: authkey1
PrivKey: privkey1

Knowing how this behaves on your side might help to reproduce it here.

**Comment by rolinux** [comment]
Getting this error:

```shell
radu@mbp13 ~/d/g/s/snmpDebug [2]> go run main.go
2020/05/26 12:45:07 Get() err: error reading from socket: read udp 192.168.7.248:65026->104.236.166.95:161: read: connection refused
exit status 1
radu@mbp13 ~/d/g/s/snmpDebug [1]> 
```

with the following code:

```go
package main

import (
	"fmt"
	"log"
	"time"

	_ "crypto/aes"
	_ "crypto/sha256"

	g "github.com/soniah/gosnmp"
)

func main() {
	params := &g.GoSNMP{
		Target:        "demo.snmplabs.com",
		Port:          161,
		Version:       g.Version3,
		Timeout:       time.Duration(30) * time.Second,
		SecurityModel: g.UserSecurityModel,
		MsgFlags:      g.AuthPriv,
		SecurityParameters: &g.UsmSecurityParameters{UserName: "usr-sha-aes",
			AuthenticationProtocol:   g.SHA256,
			AuthenticationPassphrase: "authkey1",
			PrivacyProtocol:          g.AES,
			PrivacyPassphrase:        "privkey1",
		},
	}
	err := params.Connect()
	if err != nil {
		log.Fatalf("Connect() err: %v", err)
	}
	defer params.Conn.Close()

	oids := []string{"1.3.6.1.4.1.4413.1.1.43.1.8.1.5.1.1"}
	result, err2 := params.Get(oids) // Get() accepts up to g.MAX_OIDS
	if err2 != nil {
		log.Fatalf("Get() err: %v", err2)
	}

	fmt.Printf("Debug: %v\n", result.Variables[0])
	fmt.Printf("Debug name: %v\n", result.Variables[0].Name)
	fmt.Printf("Debug value: %v\n", result.Variables[0].Value)
}
```

**Comment by soniah** [comment]
Thanks. If one of you wouldn't mind doing a PR to fix this, that'd be great.
