### ISSUE TITLE
sendOneRequest umashal err continue cause request Timeout 

### ISSUE THREAD

**Issue by phoenixfight** [gosnmp/gosnmp#246]
func (x *GoSNMP) sendOneRequest(packetOut *SnmpPacket,
	wait bool) (result *SnmpPacket, err error) {
`
			
                        cursor, err = x.unmarshalHeader(resp, result)
			if err != nil {
				x.logPrintf("ERROR on unmarshall header: %s", err)
				continue
			}

			if x.Version == Version3 {
				err = x.testAuthentication(resp, result)
				if err != nil {
					x.logPrintf("ERROR on Test Authentication on v3: %s", err)
					break
				}
				resp, cursor, _ = x.decryptPacket(resp, cursor, result)
			}

			err = x.unmarshalPayload(resp, cursor, result)
			if err != nil {
				x.logPrintf("ERROR on UnmarshalPayload on v3: %s", err)
				continue
			}
			if len(result.Variables) < 1 {
				x.logPrintf("ERROR on UnmarshalPayload on v3: %s", err)
				continue
			}

`
when marshal error , continue cause client timeout , it shoud be break?

**Comment by SuperQ** [comment]
I'm posting to all open issues that we now have a community maintainer effort going. If this issue is still valid, please post an update.

**Comment by AlexandreYang** [comment]
Having similar issue. It seems that on those cases calling `continue` will lead to this line being called a second time `resp, err = x.receive()`, that will then lead to a timeout error.

- unmarshal header: https://github.com/gosnmp/gosnmp/blob/ef8491e0dba61eb2bbb2c85e756323d585623f30/marshal.go#L289-L293
- unmarshal payload: https://github.com/gosnmp/gosnmp/blob/ef8491e0dba61eb2bbb2c85e756323d585623f30/marshal.go#L310-L314
- no variable: https://github.com/gosnmp/gosnmp/blob/ef8491e0dba61eb2bbb2c85e756323d585623f30/marshal.go#L315-L318
