### ISSUE TITLE
updatePktSecurityParameters called with non Version3 connection or packet

### ISSUE THREAD

**Issue by clarkmcc** [gosnmp/gosnmp#251]
What's the cause of this error? Looking through the code, I'm not seeing much documentation as to why I'm seeing this. The SNMP device that I'm attempting to get data from is not SNMPv3, I can get specific oids from it using `Get` but doing a `WalkAll` from a root oid is causing this issue. Looking for clarification, thanks.

**Comment by soniah** [comment]
Please see README - `11 July 2020 - I'm planning on archiving gosnmp, as maintaining it is having too much of an effect on my work and personal life. I started the fork in March 2013 and I've been working on it ever since.`

**Comment by SuperQ** [comment]
I'm posting to all open issues that we now have a community maintainer effort going. If this issue is still valid, please post an update.

**Comment by clarkmcc** [comment]
This is still an issue.

**Comment by Hipska** [comment]
Whoops, I just posted the same issue: #307 But I know where it comes from and where to fix.
