### ISSUE TITLE
"SendOneRequest" When Send A Set Request Check Response?

### ISSUE THREAD

**Issue by linzhongwumuye** [gosnmp/gosnmp#254]
```
err = x.unmarshalPayload(resp, cursor, result)
if err != nil {
	x.logPrintf("ERROR on UnmarshalPayload on v3: %s", err)
	continue
}
if len(result.Variables) < 1 {
	x.logPrintf("ERROR on UnmarshalPayload on v3: %s", err)
	continue
}
```
When Send A SetRequest,and the Response Without VarBind, the Pdu.Error Is 0.
The Code ```if len(result.Variables) < 1``` Need to Change?
For Example
```
 if packetOut.PDUType == SetRequest {
    //TODO:: check result & Variables & result.Error
 }else {
        if len(result.Variables) < 1 {
	        x.logPrintf("ERROR on UnmarshalPayload on v3: %s", err)
	        continue
        }   
  }
```

**Comment by soniah** [comment]
Hi, please see my comment in the README:

```
11 July 2020 - I'm planning on archiving gosnmp, as maintaining it is having too much of an effect on my work and personal life. I started the fork in March 2013 and I've been working on it ever since.
```

https://github.com/soniah/gosnmp/issues/247

**Comment by SuperQ** [comment]
I'm posting to all open issues that we now have a community maintainer effort going. If this issue is still valid, please post an update.

**Comment by linzhongwumuye** [comment]
This problem has been solved。At security.go,Add WriteCommunity and Change SecLookup。Because this project is on the intranet, I can't provide the code.

**Comment by linzhongwumuye** [comment]
Add "WriteCommunity" at SecurityMap and check the wirtecommunity at SecLookup。
