### ISSUE TITLE
Can gosnmp Direct analytical mib?

### ISSUE THREAD

**Issue by praisethejack** [gosnmp/gosnmp#309]
as the question,  I want to use snmp like this:
```
snmpwalk -v 2c -c public  127.0.0.1:161   UCD-SNMP-MIB::memTotalReal.0
```
rather than
```
snmpwalk -v 2c -c public  127.0.0.1:161 .1.3.6.1.2.1.2.2.1.2.2
```
Can gosnmp do it?

**Comment by SuperQ** [comment]
No, this library currently does not parse MIB files like net-snmp does.

It would be extremely nice if there was a pure Go MIB parsing library, so we wouldn't need to use CGO [like this](https://github.com/prometheus/snmp_exporter/blob/master/generator/net_snmp.go).

**Comment by StefanHauth** [comment]
I did som PoCs with https://github.com/sleepinggenius2/gosmi lately. Seemed to do the job pretty well.
