### ISSUE TITLE
Logging enabled even though `GoSNMP.Logger` is set to `nil`

### ISSUE THREAD

**Issue by AlexandreYang** [gosnmp/gosnmp#313]
Hi,

It seems the logging code might be executed even though `GoSNMP.Logger` is set to `nil`.

When `GoSNMP.Logger` is set to `nil` and `GoSNMP.validateParameters()` (called by `GoSNMP.Connect()`)  is called the first time, it will set logger to `log.New(ioutil.Discard, "", 0)`.

https://github.com/gosnmp/gosnmp/blob/1fb2203c3c7efd0460533401ea1c4572bc05d500/gosnmp.go#L289-L296

But then, when `GoSNMP.validateParameters` is called the second time, it will set `x.loggingEnabled = true`.

With `x.loggingEnabled` set to `true`, that will then trigger logging code like:

https://github.com/gosnmp/gosnmp/blob/bd1d291881777450abc4399ee2fd0bb2795eb18b/marshal.go#L118-L128

So, even if `GoSNMP. Logger` is set to `nil`, logging code like will still be called. Even though we are discarding the result of the logger, logging related code is still using some resources.

Do you know what's the reason of setting the logger to `x.Logger = log.New(ioutil.Discard, "", 0) ` ?

## Example

```
package main

import (
	g "github.com/gosnmp/gosnmp"
)

func main() {
	params := &g.GoSNMP{
		Target:    "127.0.0.1",
		Port:      uint16(1161),
		Community: "public",
		Logger:    nil,
	}
	params.Connect()  // Will set logger to `log.New(ioutil.Discard, "", 0)`
	params.Conn.Close()

	params.Connect()  // Will set `GoSNMP.loggingEnabled = true`
	// from this point, all logging code with loggingEnabled condition will be executed
	params.Conn.Close()
}
```

State of the `params` at the end:
![image](https://user-images.githubusercontent.com/49917914/112185297-62c68c80-8c00-11eb-8d27-0a7006c36613.png)

## Workaround

Setting `loggingEnabled = false` every time before `GoSNMP.Connect` is called.

**Comment by TimRots** [comment]
Thanks for the quality report @AlexandreYang.

Guessing that the intended behavior was to override default logging for one conection, not sure if the ``set -> connect() -> close() -> connect() -> close()`` flow was intended to work as you expect here.

> Do you know what's the reason of setting the logger to x.Logger = log.New(ioutil.Discard, "", 0) ?

I don't know. The specific code is up for a brush-up as ``ioutil.Discard`` is deprecated as per go 1.16 anyway.

Do you have any solutions in mind?  Would it be helpful to have ``loggingEnabled`` exported?

**Comment by AlexandreYang** [comment]
> Guessing that the intended behavior was to override default logging for one conection, not sure if the `set -> connect() -> close() -> connect() -> close()` flow was intended to work as you expect here.

That's an interesting point. In our case, we use the same `GoSNMP` instance multiple times (every 15-60 secs). At every 15-60 secs, we do `connect() -> some snmp calls -> close()`. The connection to close here seems to be an instance of `UDPConn` and call closing `close()` will close/free the underlying file descriptor.

Another way to deal with that might be to 1/ use the same connection and not close it, but that will keep the file description in use even at idle time, or 2/ recreate a new `GoSNMP` each time.

> Do you have any solutions in mind? Would it be helpful to have loggingEnabled exported?

Ideally, In case `x.Logger = log.New(ioutil.Discard, "", 0)` is not needed, just removing that might fix the issue. But some investigation needed to be sure it won't cause any issue. I can have a deeper look at this.

**Comment by TimRots** [comment]
Hi Alexander.

> Another way to deal with that might be to 1/ use the same connection and not close it, but that will keep the file description in use even at idle time, or 2/ recreate a new `GoSNMP` each time.

I feel that the second option would be most conform on how this feature is used.
Wondering if the specific flow you named was used as performance optimization?

> Ideally, In case `x.Logger = log.New(ioutil.Discard, "", 0)` is not needed, just removing that might fix the issue. But some investigation needed to be sure it won't cause any issue. I can have a deeper look at this.

Simply removing the logger won't work as it will cause nil pointer de-references due to dependencies in ``helper.go``

I've updated the related code path to get rid of the double locking in [this](https://github.com/gosnmp/gosnmp/pull/318) PR. Do you think we need to also explicitly set ``loggingEnabled`` to false in the flow where we want to discard logging?

**Comment by AlexandreYang** [comment]
> Wondering if the specific flow you named was used as performance optimization?

Mostly to avoid having to create a new instance of `GoSNMP` each time with the same parameters.

> Simply removing the logger won't work as it will cause nil pointer de-references due to dependencies in helper.go

Maybe we can refactor dependencies like `helper.go` to only log if logger is not nil. e.g.

```
func parseRawField(logger Logger, data []byte, msg string) (interface{}, int, error) {
	if len(data) == 0 {
		return nil, 0, fmt.Errorf("empty data passed to parseRawField")
	}
	logger.Printf("parseRawField: %s", msg)

```

Possibly using a helper function like this one below to avoid repeating `logger != nil` :
```
func logPrint(logger Logger, v ...interface{}) {
	if logger != nil {
		logger.Print(v...)
	}
}
```

We can also replace all occurrences of `GoSNMP.logPrint(...)` to `logPrint(GoSNMP.logger, ...)` (same for logPrintf).

> I've updated the related code path to get rid of the double locking in this PR.

Thanks.

> Do you think we need to also explicitly set loggingEnabled to false in the flow where we want to discard logging?

I feel that if we can avoid having to set the logger to `ioutil.Discard`, there is possibly no need to have `loggingEnabled` flag at all since we can rely on logger being nil or not. If logger is nil, do not log, otherwise call `logger.Print/Printf` (example helper function above).
If seems `loggingEnabled` is needed currently because we can't rely on logger nil state.

**Comment by it1804** [comment]
Please see my solution to the logging problem https://github.com/gosnmp/gosnmp/pull/329
