### ISSUE TITLE
use example 3 get() err

### ISSUE THREAD

**Issue by cappuccino5** [gosnmp/gosnmp#315]
package main

import (
	"fmt"
	"log"
	
	g "github.com/gosnmp/gosnmp"
)

func main() {
	
	// build our own GoSNMP struct, rather than using g.Default
	params := &g.GoSNMP{
		Target:        "192.168.1.113",
		Port:          161,
		Version:       g.Version3,
		SecurityModel: g.UserSecurityModel,
		MsgFlags:      g.AuthPriv,
		SecurityParameters: &g.UsmSecurityParameters{UserName: "user",
			AuthenticationProtocol:   g.MD5,
			AuthenticationPassphrase: "myPassword",
			PrivacyProtocol:          g.DES,
			PrivacyPassphrase:        "myPassword",

		},
	}
	err := params.Connect()
	if err != nil {
		log.Fatalf("Connect() err: %v", err)
	}
	defer params.Conn.Close()
	
	oids := []string{"1.3.6.1.2.1.1.5.0","1.3.6.1.2.1.1.1.0"}
	result, err2 := params.Get(oids) // Get() accepts up to g.MAX_OIDS
	if err2 != nil {
		log.Fatalf("Get() err: %v", err2)
	}
	
	for i, variable := range result.Variables {
		fmt.Printf("%d: oid: %s ", i, variable.Name)
		
		// the Value of each variable returned by Get() implements
		// interface{}. You could do a type switch...
		switch variable.Type {
		case g.OctetString:
			fmt.Printf("string: %s\n", string(variable.Value.([]byte)))
		default:
			// ... or often you're just interested in numeric values.
			// ToBigInt() will return the Value as a BigInt, for plugging
			// into your calculations.
			fmt.Printf("number: %d\n", g.ToBigInt(variable.Value))
		}
	}
}

show one err 
![image](https://user-images.githubusercontent.com/40583480/112599076-62213680-8e4a-11eb-9511-f152a687ced0.png)

server centos7.8
gosnmp  version is latest 1.30.0

i think my need help， thanks!

**Comment by cappuccino5** [comment]
I use example/main.go is normal .

I don't know if example 3 has been deprecated, but if so, I'm sorry to interrupt

**Comment by TimRots** [comment]
Hi @cappuccino5 , it should work if you add the timeout property like ``Timeout:       time.Duration(30) * time.Second,``.

Example 3 will be fixed by #316
