### ISSUE TITLE
how to check if the value is hex-sting

### ISSUE THREAD

**Issue by KM612** [gosnmp/gosnmp#325]
Hi,  when I get a OctetString, I want to now it is a normal string or a hex-sting(like mac adress) 。how can I do.

**Comment by SuperQ** [comment]
This is determined by the MIBs. There are dozens of "Textual Conventions" that hint what kind of data will be in the OctetString. There is no information in SNMP itself about this.

**Comment by KM612** [comment]
> This is determined by the MIBs. There are dozens of "Textual Conventions" that hint what kind of data will be in the OctetString. There is no information in SNMP itself about this.

thank you.
