### ISSUE TITLE
if gosnmp.Default.Logger is nil, the application will crash

### ISSUE THREAD

**Issue by ZhouYing-bit** [gosnmp/gosnmp#327]
version: github.com/gosnmp/gosnmp v1.31.0

![image](https://user-images.githubusercontent.com/13702789/115845638-a0af0e80-a453-11eb-8e6e-8a82d79214ad.png)

**Comment by cemremengu** [comment]
Are you explicitly setting it to `nil`? I am not getting such an error. Would be great if you can share some of your code.

**Comment by TimRots** [comment]
Windows is unsupported/tested. Can you still share some code on how you trigger this @ZhouYing-bit?
