### ISSUE TITLE
how to handle no server available

### ISSUE THREAD

**Issue by felixn-unity** [gosnmp/gosnmp#336]
Hi

What is the best way to prevent stuff to timeout when sending SNMP packages to a host that is not online?

Thanks
Felix

**Comment by TimRots** [comment]
You could better ask such on #snmp channel of [Gophers Slack](https://invite.slack.golangbridge.org/).

**Comment by FlexyZ-xx** [comment]
thanks for nothing

**Comment by SuperQ** [comment]
@FlexyZ-xx You're welcome!
