### ISSUE TITLE
How to bind to IP address

### ISSUE THREAD

**Issue by marunguy** [gosnmp/gosnmp#339]
How to bind to IP address?

My PC have two nics - one: 10.1.1.20, other: 192.168.1.30
Each nic is connected to different network.

I want to bind gosnmp to 192.168.1.30.
How can I do it?
```go
package main

import (
	"fmt"
	"log"

	gosnmp "github.com/gosnmp/gosnmp"
)

func main() {
	fmt.Printf("start\n")

	var snmpInst gosnmp.GoSNMP = *gosnmp.Default
	snmpInst.Target = "192.168.1.50"
	// bind snmpInst to 192.168.1.30 ?????
	// snmpInst.Source = "192.168.1.30" ?????

	err := snmpInst.Connect()
	if err != nil {
		log.Fatalf("Connect() err: %v", err)
	}
	defer snmpInst.Conn.Close()

	oids := []string{"1.3.6.1.2.1.1"}
	result, err2 := snmpInst.GetNext(oids)
	if err2 != nil {
		log.Fatalf("Get() err: %v", err2)
	}

	for i, variable := range result.Variables {
		fmt.Printf("%d: oid: %s ", i, variable.Name)

		switch variable.Type {
		case gosnmp.OctetString:
			fmt.Printf("string: %s\n", string(variable.Value.([]byte)))
		default:
			fmt.Printf("number: %d\n", gosnmp.ToBigInt(variable.Value))
		}
	}
}
```

**Comment by it1804** [comment]
You cannot bind to a specific ip. But you can tell gosnmp to listen on the port. If everything is in order with the routing, there should be no problems. I have a similar configuration with multiple network adapters and static routes to specific subnets via specific network adapters.
```snmpInst.UseUnconnectedUDPSocket = true```

**Comment by it1804** [comment]
A prototype patch that should fix the problem https://github.com/gosnmp/gosnmp/pull/342
