### ISSUE TITLE
Document an SNMP Set example

### ISSUE THREAD

**Issue by TJ-F** [gosnmp/gosnmp#352]
Could someone please show an example of a SNMP Set? I cannot find any examples currently.

**Comment by nwaizer** [comment]
Same for me,
I have this command to power-on a APC Power socket:
snmpset -v2c -c private 10.46.61.226 1.3.6.1.4.1.318.1.1.4.4.2.1.3.15 i 1

how to achieve this using gosnmp?
I am checking the socket status and power it on, if it is off.

`import g "github.com/gosnmp/gosnmp"

const (
	On  int = 1
	Off     = 2
)

g.Default.Target = "10.46.61.226"
	err := g.Default.Connect()
	if err != nil {
		log.Fatalf("Connect() err: %v", err)
	}
	defer g.Default.Conn.Close()
	socketOid := "1.3.6.1.4.1.318.1.1.4.4.2.1.3.15"
	oids := []string{socketOid}
	result, err2 := g.Default.Get(oids)
	if err2 != nil {
		log.Fatalf("Get() err: %v", err2)
	}
	fmt.Printf("socket 15 status is: %v\n", result.Variables[0].Value)
	socketStats := result.Variables[0].Value
	if socketStats == Off {
		log.Warnf("Socket 15 is Off, power it on.")
		var mySnmpPDU []g.SnmpPDU
		mySnmpPDU = append(mySnmpPDU, g.SnmpPDU{
			Name:  socketOid,
			Type:  g.Integer,
			Value: On,
		})
		setResult, setErr := g.Default.Set(mySnmpPDU)
		if setErr != nil {
			panic(setErr)
		}
		fmt.Printf("When setting the socket on I got this result: %v\n", &setResult)
	}`

**Comment by TJ-F** [comment]
@nwaizer - This worked for me:
```package main

import (
	"fmt"
	"log"

	g "github.com/gosnmp/gosnmp"
)

var a_oid = []g.SnmpPDU{g.SnmpPDU{
	Name:  "1.3.6.1.4.1.37069.1.1.2.0",
	Type:  g.Integer,
	Value: 0}}

func main() {

	g.Default.Target = "10.2.26.96"
	err := g.Default.Connect()
	if err != nil {
		log.Fatalf("Connect() err: %v", err)
	}
	defer g.Default.Conn.Close()

	result, err2 := g.Default.Set(a_oid)

	if err2 != nil {
		log.Fatalf("Set() err: %v", err2)
	}

	for i, variable := range result.Variables {
		fmt.Printf("%d: oid: %s ", i, variable.Name)

		// the Value of each variable returned by Get() implements
		// interface{}. You could do a type switch...
		switch variable.Type {
		case g.OctetString:
			fmt.Printf("string: %s\n", string(variable.Value.([]byte)))
		default:
			// ... or often you're just interested in numeric values.
			// ToBigInt() will return the Value as a BigInt, for plugging
			// into your calculations.
			fmt.Printf("number: %d\n", g.ToBigInt(variable.Value))
		}
	}
}

**Comment by nwaizer** [comment]
var a_oid = []g.SnmpPDU{g.SnmpPDU{ 

should be
var a_oid := []g.SnmpPDU{g.SnmpPDU{

**Comment by nwaizer** [comment]
FATA[0031] Set() err: request timeout (after 3 retries) 
How to increase timeout?

**Comment by TJ-F** [comment]
Check examples 2 and 3. or add `g.Default.Timeout = time.Duration(6)*time.Second`

	// Build our own GoSNMP struct, rather than using g.Default.
	// Do verbose logging of packets.
	params := &g.GoSNMP{
		Target:    envTarget,
		Port:      uint16(port),
		Community: "public",
		Version:   g.Version2c,
		Timeout:   time.Duration(2) * time.Second,
		Logger:    g.NewLogger(log.New(os.Stdout, "", 0)),
	}

**Comment by nwaizer** [comment]
@TJ-F  please accept my donation https://github.com/gosnmp/gosnmp/pull/396 in return for your help
