### ISSUE TITLE
Marshaling integer values doesn't satisfy ITU-T Rec. X.690 (07/2002)

### ISSUE THREAD

**Issue by ghost** [gosnmp/gosnmp#371]
Maybe I'm wrong, but the test data for marshaling int32 values is not correct in the following part:

var testsMarshalInt32 = []struct {
  value     int
  goodBytes []byte
}{
  ...
  {-65537, []byte{0xff, 0xfe, 0xff, 0xff}},
  {-65536, []byte{0xff, 0xff, 0x00, 0x00}},
  {-257, []byte{0xff, 0xff, 0xfe, 0xff}},
  {-256, []byte{0xff, 0xff, 0xff, 0x00}},
  {-2, []byte{0xff, 0xff, 0xff, 0xfe}},
  {-1, []byte{0xff, 0xff, 0xff, 0xff}},
}

According to ITU-T Rec. X.690 (07/2002):

8.3.2 If the contents octets of an integer value encoding consist of more than one octet,
then the bits of the first octet and bit 8 of the second octet:
  a) shall not all be ones; and 
  b) shall not all be zero. 
NOTE – These rules ensure that an integer value is always encoded in the smallest possible number of octets.

Meanwhile, in the test data part all goodBytes starts with 0xff, 0xff, i.e. doesn't satisfy a+b) requirement.

I use another marshaling code which gives:

  {-65537, []byte{0xfe, 0xff, 0xff}},
  {-65536, []byte{0xff, 0x00, 0x00}},
  {-257, []byte{0xfe, 0xff}},
  {-256, []byte{0xff, 0x00}},
  {-2, []byte{0xfe}},
  {-1, []byte{0xff}},

**Comment by it1804** [comment]
This seems to be the case for all variables with INTEGER type. I found in the dump traffic snippets that at least the RequestID is encoded according to the same rules. For example, ciscoResponseBytes in marshal_test.go is encoded in 3 bytes, not 4.
