### ISSUE TITLE
SET objects

### ISSUE THREAD

**Issue by gmonk** [gosnmp/gosnmp#375]
I noticed that I am no longer able to set  Object Identifiers. Is there a reason this was removed  ?  In the previous version of soniah 1.26 this was the code 

func (x *GoSNMP) Set(pdus []SnmpPDU) (result *SnmpPacket, err error) {
	var packetOut *SnmpPacket
	switch pdus[0].Type {
	// TODO test Gauge32
	case Integer, OctetString, Gauge32, IPAddress, ObjectIdentifier:
		packetOut = x.mkSnmpPacket(SetRequest, pdus, 0, 0)
	default:
		return nil, fmt.Errorf("ERR:gosnmp currently only supports SNMP SETs for Integers, IPAddress and OctetStrings")
	}
	return x.send(packetOut, true)

Could this be added back ?  I'm not sure why it would matter either way since the pdu type is specified on creation and then sent out. Unless there is a reason for it being removed.  

Thanks

**Comment by it1804** [comment]
I was looking for a reason why support might have been removed in some version, but I have not seen in the repository that the ObjectIdentifier for Set() was ever resolved. It is not available in version 1.26.
But, apparently, nothing prevents you from adding, simply adding in the this switch-case
