### ISSUE TITLE
Unable to marshal varbind list

### ISSUE THREAD

**Issue by Derek-K** [gosnmp/gosnmp#388]
Since I did an apt upgrade yesterday, one of my telegraf snmp probes stopped working. After a few hours of debugging and google around, the error seems to point here

"telegraf --test --debug" output
```
[inputs.snmp] Error in plugin: agent udp://xxx.xxx.xxx.xxx:xxx: performing get on field model: marshal: marshalPDU: unable to marshal varbind list: unable to marshal OID: Invalid object identifier
```

There was no change to my configs. And it was an SNMPv1 endpoint (specify an old APC UPS). 

I have done a snmpwalk and everything seems to be ok.

**Comment by it1804** [comment]
I also use gosnmp, but one thing is for sure. Gosnmp does not work at any level with MIBs definitions, only raw OIDs. 
It looks like the problem is at a higher level, and is related to invalid translation of MIB->OID

**Comment by MyaLongmire** [comment]
This issue is not related to gosnmp. There is a pr in the telegraf repository to fix this.
