### ISSUE TITLE
Chinese coding is garbled

### ISSUE THREAD

**Issue by CosmosNi** [gosnmp/gosnmp#428]
when i try receive data 

snmptrap -v 2c -c public 127.0.0.1:9162 12345 1.3.6.1.6.3.1.1.4.1.100 1.3.6.1.4.1.49022.4.2.11 s opstest告警服务器 

![image](https://user-images.githubusercontent.com/40288034/217169567-3fa1a177-4ef7-4ba0-b1d2-fcb37b7d0c98.png)

**Comment by SuperQ** [comment]
What code are you using to decode this? The example trapserver? The example code just uses `%x` formatting for the incoming OCTET STRING, since SNMP does not define any character encoding as part of the protocol. You can't tell from the trap if it should be ASCII, UTF-8, or some other encoding.

**Comment by CosmosNi** [comment]
> What code are you using to decode this? The example trapserver? The example code just uses `%x` formatting for the incoming OCTET STRING, since SNMP does not define any character encoding as part of the protocol. You can't tell from the trap if it should be ASCII, UTF-8, or some other encoding.

Sorry, the problem is caused by the default encoding gbk of window

I also want to ask why oid has one，i send 1.3.6.1.4.1.49022.4.2.12,but get .1.3.6.1.4.1.49022.4.2.12
