### ISSUE TITLE
marshal: marshalPDU: unable to marshal varbind list: unable to marshal OID: Value out of range

### ISSUE THREAD

**Issue by seankndy** [gosnmp/gosnmp#431]
I have several SNMP agents (networking devices) that have SNMP interface ID values that are >32bit integers in size.  I am unable to query them using the gosnmp library because the `marshalObjectIdentifier` func in helper.go returns an error if a sub-identifier is >32bit integer with "Value out of range".  An example OID is `IF-MIB::ifHCInOctets.120010106` (`.1.3.6.1.2.1.31.1.1.1.6.120010106`).

I see that https://www.rfc-editor.org/rfc/rfc2578#section-7.1.3 states that these values shouldn't ever exceed a 32bit integer, however the snmpget tool allows this and it works:

```
$ snmpget -On -v2c -c public 10.19.208.41 ifHCInOctets.120010106
.1.3.6.1.2.1.31.1.1.1.6.120010106 = Counter64: 6825663129553
```

This particular device is a Calix E7.  I also have some Extreme Networks switches that use >32bit interface ID values and thus are not working with gosnmp as well.

I am not familiar enough with the SNMP standard to comment on this, but I would appreciate any feedback from the developers of gosnmp library regarding the issue.

**Comment by SuperQ** [comment]
The value you have there, 120010106, is well within 32-bit int range (0 to 4294967295).

Can you include the code you are using and the full error message?

**Comment by seankndy** [comment]
Man, you're absolutely right.  I found my issue and its not related to gosnmp at all.   My network equipment's IF-IDs are indeed <32bit as well.  I just got lost between all the cross referencing and copying and pasting and didn't even think to really stop and look at the value during my troubleshooting.

I am very sorry for wasting your time.
