### ISSUE TITLE
out of bounds error when parsing AuthNoPriv packet

### ISSUE THREAD

**Issue by matan-cylus** [gosnmp/gosnmp#433]
**Issue Description:**
In the file `v3_usm.go`, there is an issue with accessing the payload at line 880 in version 1.27.0 (or line 1006, 740 in the current master version). The updated version of the library accesses the payload the following way: `packet[cursor+2:cursor+len(macVarbinds[sp.AuthenticationProtocol])].`
However, when the payload has a zero value authentication protocol, the updated version throws an out of bounds error because: `len(macVarbinds[sp.AuthenticationProtocol]) = 0`.
This issue occurs only when the message flags are set to `AuthNoPriv`.

**Steps to Reproduce:**
[snmp_packet.zip](https://github.com/gosnmp/gosnmp/files/11529423/snmp_packet.zip)

Use the `gosnmp` library version 1.27.0 (or the current master version).
Decode the SNMP payload (see pcap in issue) using `SnmpDecodePacket() `.

**Additional Information:**
This issue is specific to version 1.27.0 (or the current master version) of the `gosnmp` library. It affects the `v3_usm.go` file and occurs only when the message flags are set to `AuthNoPriv`

**Comment by TimRots** [comment]
Thanks you for the report @matan-cylus
I need some time to dig into the details and will get back here.

**Comment by TimRots** [comment]
hi @matan-cylus , Could you share me how you trigger the mentioned bug with below code that I generated from the pcap that you shared?
```go
// Simple Network Management Protocol
//
//	msgVersion: snmpv3 (3)
//	msgGlobalData
//	    msgID: 37321
//	    msgMaxSize: 2048
//	    msgFlags: 07
//	        .... .1.. = Reportable: Set
//	        .... ..1. = Encrypted: Set
//	        .... ...1 = Authenticated: Set
//	    msgSecurityModel: USM (3)
//	msgAuthoritativeEngineID: 000039e7000000a1c0a81da0
//	    0... .... = Engine ID Conformance: RFC1910 (Non-SNMPv3)
//	    Engine Enterprise ID: Aruba, a Hewlett Packard Enterprise company (14823)
//	    AgentID Trailer: 000000a1c0a81da0
//	msgAuthoritativeEngineBoots: 752
//	msgAuthoritativeEngineTime: 196071
//	msgUserName: admin
//	msgAuthenticationParameters: ac1663903625bedee6f32466
//	msgPrivacyParameters: cb26d90073efc352
//	msgData: encryptedPDU (1)
//	    encryptedPDU: 14094a43804d88fc6f523fe1b2aa27dc1faf23afdf770307ec27291d55348436405a858e…
func v3AuthNoPrivOOB() []byte {
	return []byte{
		0x30, 0x7f, 0x02, 0x01, 0x03, 0x30, 0x0f, 0x02, 0x03, 0x00, 0x91, 0xc9,
		0x02, 0x02, 0x08, 0x00, 0x04, 0x01, 0x07, 0x02, 0x01, 0x03, 0x04, 0x38,
		0x30, 0x36, 0x04, 0x0c, 0x00, 0x00, 0x39, 0xe7, 0x00, 0x00, 0x00, 0xa1,
		0xc0, 0xa8, 0x1d, 0xa0, 0x02, 0x02, 0x02, 0xf0, 0x02, 0x03, 0x02, 0xfd,
		0xe7, 0x04, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x04, 0x0c, 0xac, 0x16,
		0x63, 0x90, 0x36, 0x25, 0xbe, 0xde, 0xe6, 0xf3, 0x24, 0x66, 0x04, 0x08,
		0xcb, 0x26, 0xd9, 0x00, 0x73, 0xef, 0xc3, 0x52, 0x04, 0x2f, 0x14, 0x09,
		0x4a, 0x43, 0x80, 0x4d, 0x88, 0xfc, 0x6f, 0x52, 0x3f, 0xe1, 0xb2, 0xaa,
		0x27, 0xdc, 0x1f, 0xaf, 0x23, 0xaf, 0xdf, 0x77, 0x03, 0x07, 0xec, 0x27,
		0x29, 0x1d, 0x55, 0x34, 0x84, 0x36, 0x40, 0x5a, 0x85, 0x8e, 0xb2, 0x3a,
		0x56, 0xb1, 0x57, 0x71, 0x6e, 0xb8, 0x5a, 0x51, 0x43,
	}
}
```

I think i managed to trigger another bug with this elsewhere in v3_usm.go, but am particularity interested in your issue.
