### ISSUE TITLE
Compatibility with GoSNMPServer

### ISSUE THREAD

**Issue by upsampled** [gosnmp/gosnmp#446]
[github.com/slayercat/GoSNMPServer](https://github.com/slayercat/GoSNMPServer/) forked `gosnmp/gosnmp` and made it is own package [github.com/slayercat/gosnmp](https://github.com/slayercat/gosnmp). While there were a lot of aesthetic changes, as far as I can tell, the primary change needed was for the server to easily increment the private random counter used as a salt (`GenSalt`) for generating encryption keys (`GenKey`).  

Anyhow fast forward 3 years and GoSNMPServer is failing to implement more advanced encryption (specifically hashing) because the fork has stagnated. PR to follow.

**Comment by upsampled** [comment]
@SuperQ  just to summarize the comments in the PR, for `slayercat/GoSNMPServer` to work with mainline `gosnmp/gosnmp` instead of the dated `slayercat/gosnmp` fork (with minimal changes to both), `gosnmp/gosnmp` would need to accept either:

* making the USM salt members public - would not change the gosnmp API at all, but would require a kludgy fix in the `GoSNMPServer` 
* adding the GenSalt/GenKey methods - adds to the existing API, really does not have a use-case besides GoSNMPServer, but is at least straight forward in purpose and use. 

Allowing one of these changes will at least keep the only public Go SNMP Server implementation (that I know of at least) up to date.

**Comment by slayercat** [comment]
Thank you to the project team for discussing this issue. . Your assistance on this matter is greatly appreciated.

I am pleased and eager to contribute further to its resolution.

**Comment by upsampled** [comment]
@slayercat I am having one slight additional issue porting `GoSNMPServer` to `gosnmp\gosnmp`, I do the following:

1. Add GenKey and GenSalt to a fork of `gosnmp/gosnmp` #447 
2. I then update update the imports in `GoSNMPServer` 
3. Also in `GoSNMPServer`, I update Logger instance in GoSNMP (basically `&SnmpLoggerAdapter` to `gosnmp.NewLogger`) and a few other minor changes

At this point the test program for GoSNMPServer can run, supporting SHA256 and AES256; however, `snmpwalk` fails on it's second OID. I found that by changing the below I can get more output from `snmpwalk` but will eventually get an OID not incrementing error.  

```diff
--- a/snmp/GoSNMPServer/agentcontrolSubAgent.go
+++ b/snmp/GoSNMPServer/agentcontrolSubAgent.go
@@ -450,7 +450,7 @@ func (t *SubAgent) serveSetRequest(i *gosnmp.SnmpPacket) (*gosnmp.SnmpPacket, er

 func (t *SubAgent) getForPDUValueControl(oid string) (*PDUValueControlItem, int) {
        // todo: maybe we can implement add "." at other place.
-       toQuery := "." + oidToByteString(oid)
+       toQuery := oidToByteString(oid)
        i := sort.Search(len(t.OIDs), func(i int) bool {
                thisOid := oidToByteString(t.OIDs[i].OID)
                return thisOid >= toQuery
```


I do not get this error when GoSNMPServer is using `slayercat/gosnmp`. Do you have any idea what the issue is? Does `gosnmp/gosnmp` need an additional change to support GoSNMPServer?

**Comment by slayercat** [comment]
@upsampled 

I apologize for not noticing this issue earlier.

This appears to be a bug introduced by the commit e5e512ec64b25cec8820baa669d9a270b1705ab0. I will take a closer look at it later.

**Comment by slayercat** [comment]
Thank you, @upsampled.

I believe that the commit https://github.com/slayercat/GoSNMPServer/commit/f220d18995267b7e1ad44a23fb1239e6741eeaa1 fixed the issue you mentioned. Please feel free to give it a try.

While attempting to compile using MR #447, I noticed some differences in the Logger and other interfaces compared to the previous changes. I believe this may require some adaptation work.

If you have any suggestions, please let me know. I'm glad to make the necessary modifications.

**Comment by upsampled** [comment]
@slayercat that patch works! Give me a few days to clean up the 'gosnmp' PR and then I'll publish my fork of `GoSNMPServer` that points to it

**Comment by upsampled** [comment]
Ok put in the changes that @TimRots suggested and have a branch of GoSNMPServer working with it here: https://github.com/upsampled/GoSNMPServer/tree/GoSNMPServer%2320

Assuming the PR gets accepted, @slayercat I'll turn that GoSNMPServer branch into a PR
