### ISSUE TITLE
OID index in tabular oid result

### ISSUE THREAD

**Issue by ThakkarChandresh** [gosnmp/gosnmp#470]
I'm using snmp walk to get the result of the tabular oids, and then map the value according to the result returned by walk,

I'm facing error related mapping the different oid results, like I'm using these oids to get accesspoint details

".1.3.6.1.4.1.14179.2.2.1.1.3":    AccessPoint,
".1.3.6.1.4.1.14179.2.2.1.1.19":   AccessPointIP,
".1.3.6.1.4.1.14179.2.2.1.1.4":    AccessPointLocation,
".1.3.6.1.4.1.14179.2.2.1.1.1":    AccessPointMACAddress,

I'm using walk function on all above oids and then want to map the data row wise,

Assuming these oid returns 10 APs so how to identify that which AccessPoint maps with AccessPointIP?

In EasySNMP they return the oid index with each walk result based on which i do the mapping.

So is there any way to map these oid result?

**Comment by SuperQ** [comment]
Have you looked at the [snmp_exporter](https://github.com/prometheus/snmp_exporter)?

**Comment by ThakkarChandresh** [comment]
Yes, but i want to use gosnmp's walk function.
