### ISSUE TITLE
Question: optimize performance

### ISSUE THREAD

**Issue by andvary** [gosnmp/gosnmp#473]
I want to communicate with a large number of devices (up to 10 000) by SNMP (Get and GetBulk requests), so could you please answer a few questions about optimizing performance while using gosnmp?

- Is it safe to use multiple workers with a separate GoSNMP struct per worker?
- Is it possible to re-use UDP sockets and just plug a new Target to the GoSNMP struct used by a specific worker every time I send a request to a new device?

**Comment by SuperQ** [comment]
Yes, it's possible to have multiple GoSNMP structs running concurrently. Take a look at the [snmp_exporter scraper package](https://github.com/prometheus/snmp_exporter/tree/main/scraper) if you want some examples of how this library can be used.

**Comment by andvary** [comment]
Thanks!
